# .gitpod.yml
# Terraform + AWS CLI v2 auto-setup for Gitpod (works with standard + ONA)
# -----------------------------------------------------------------------------
# HOW TO USE:
# 1) Commit this file at the repo root.
# 2) In Gitpod → Settings → Variables, add:
#    - AWS_ACCESS_KEY_ID
#    - AWS_SECRET_ACCESS_KEY
#    - AWS_DEFAULT_REGION     (e.g., us-east-1)
#    - Optional: AWS_SESSION_TOKEN (if you use temporary creds)
# 3) Start a new Gitpod workspace.

image:
  # You can change this to another base image if you prefer.
  # Using workspace-full gives you common dev tools out of the box.
  file: .gitpod.Dockerfile

# If you don't want a Dockerfile, comment out the 'image' block above
# and keep the tasks below—everything will still install at runtime.

tasks:
  - name: Setup Terraform & AWS CLI
    # 'init' runs on prebuild/first start. Keep heavy installs here.
    init: |
      set -euo pipefail
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends \
        gnupg software-properties-common lsb-release ca-certificates curl unzip

      # --- Install Terraform from the official HashiCorp APT repo ---
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list >/dev/null
      sudo apt-get update
      sudo apt-get install -y terraform

      # --- Install AWS CLI v2 ---
      curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -q awscliv2.zip
      sudo ./aws/install --update
      rm -rf aws awscliv2.zip
    # 'command' runs on every workspace start (fast checks, env wiring).
    command: |
      set -euo pipefail
      echo "Terraform: $(terraform version | head -n1)"
      echo "AWS CLI: $(aws --version)"
      # Set default region for this workspace if provided via Gitpod Variables
      if [ -n "${AWS_DEFAULT_REGION:-}" ]; then
        aws configure set default.region "$AWS_DEFAULT_REGION"
      fi
      # Optional: confirm identity if creds are present (won't fail the workspace)
      if [ -n "${AWS_ACCESS_KEY_ID:-}" ]; then
        aws sts get-caller-identity || true
      fi

# Helpful editor extensions
vscode:
  extensions:
    - hashicorp.terraform
    - amazonwebservices.aws-toolkit-vscode
    - redhat.vscode-yaml
    - eamodio.gitlens

# Optional: prebuilds speed up first-time workspace starts for your team.
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addBadge: false
